version: '3.3'
volumes:
  media:
  static:
  pg_data:
services:
  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: ../.env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    container_name: foodgram-proxy
    build: ../nginx
    ports:
      - "80:80"
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - backend
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
